# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YFP7AB9TED-hb3IlzHyyeggDj0HifjB5
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta

np.random.seed(42)

# 1. Справочник пива
beers = pd.DataFrame([
    {"beer_id": 1, "beer_name": "Helles Classic", "style": "Lager", "cost_per_l": 1.2, "price_per_l": 4.5, "shelf_life_days": 90},
    {"beer_id": 2, "beer_name": "Bavarian Weiss", "style": "Wheat", "cost_per_l": 1.4, "price_per_l": 4.8, "shelf_life_days": 60},
    {"beer_id": 3, "beer_name": "Hop Explosion", "style": "IPA", "cost_per_l": 2.1, "price_per_l": 6.5, "shelf_life_days": 45},
    {"beer_id": 4, "beer_name": "Midnight Porter", "style": "Stout", "cost_per_l": 1.9, "price_per_l": 5.8, "shelf_life_days": 120},
    {"beer_id": 5, "beer_name": "Tropical Sour", "style": "Sour", "cost_per_l": 2.3, "price_per_l": 7.0, "shelf_life_days": 30},
    {"beer_id": 6, "beer_name": "Amber Ale", "style": "Ale", "cost_per_l": 1.5, "price_per_l": 5.0, "shelf_life_days": 75},
])

# 2. Справочник баров
cities = ["Hamburg", "Berlin", "Munich", "Cologne", "Frankfurt", "Hannover"]
bar_types = ["Craft Taproom", "Traditional Pub", "Restaurant", "Sports Bar"]
bars = pd.DataFrame([
    {
        "bar_id": i,
        "bar_name": f"Bar #{i} {np.random.choice(['Craft', 'Pub', 'Brauhaus'])}",
        "city": np.random.choice(cities),
        "bar_type": np.random.choice(bar_types)
    } for i in range(1, 31)
])

# 3. Справочник пивоварен
breweries = pd.DataFrame([
    {"brewery_id": 1, "brewery_name": "Hamburg Craft Lab", "city": "Hamburg", "capacity_l_month": 50000},
    {"brewery_id": 2, "brewery_name": "Bavaria Brewhouse", "city": "Munich", "capacity_l_month": 80000},
    {"brewery_id": 3, "brewery_name": "Berlin Ale Works", "city": "Berlin", "capacity_l_month": 60000},
    {"brewery_id": 4, "brewery_name": "Rheinland Brewery", "city": "Cologne", "capacity_l_month": 45000},
    {"brewery_id": 5, "brewery_name": "Frankfurt Craft Co", "city": "Frankfurt", "capacity_l_month": 40000},
])

# 4. Генерация факт-таблицы варок (fact_batches)
start_date = datetime(2025, 1, 1)
end_date = datetime(2026, 6, 30)

batches_list = []
batch_id = 1001

# Генерируем варки каждые несколько дней на разных пивоварнях
current_date = start_date
while current_date <= end_date:
    num_batches = np.random.randint(1, 4)
    for _ in range(num_batches):
        beer = beers.sample(1).iloc[0]
        brewery = breweries.sample(1).iloc[0]
        volume_brewed = np.random.choice([1000, 2000, 3000, 5000])

        batches_list.append({
            "batch_id": batch_id,
            "brew_date": current_date.strftime('%Y-%m-%d'),
            "brewery_id": brewery["brewery_id"],
            "beer_id": beer["beer_id"],
            "volume_brewed_l": volume_brewed,
            "expiry_date": (current_date + timedelta(days=int(beer["shelf_life_days"]))).strftime('%Y-%m-%d')
        })
        batch_id += 1
    current_date += timedelta(days=np.random.randint(1, 3))

batches_df = pd.DataFrame(batches_list)

# 5. Генерация факт-таблицы продаж (fact_sales)
date_range = pd.date_range(start_date, end_date, freq='D')
sales_list = []
sales_id = 1

for date in date_range:
    weekend_mult = 1.5 if date.weekday() >= 4 else 1.0
    season_mult = 1.3 if date.month in [6, 7, 8] else 1.0

    num_transactions = int(np.random.randint(15, 35) * weekend_mult)

    for _ in range(num_transactions):
        beer = beers.sample(1).iloc[0]
        bar = bars.sample(1).iloc[0]

        volume_l = round(np.random.uniform(20, 100), 1)
        temp = round(np.random.normal(6, 2.5), 1)

        spoil_risk = 0.25 if temp > 9 else 0.03
        spoil_volume_l = round(volume_l * np.random.uniform(0.1, 0.4), 1) if np.random.rand() < spoil_risk else 0.0

        sales_list.append({
            "sales_id": sales_id,
            "date": date.strftime('%Y-%m-%d'),
            "bar_id": bar["bar_id"],
            "beer_id": beer["beer_id"],
            "volume_liters": volume_l,
            "spoil_volume_liters": spoil_volume_l,
            "transport_temp_c": temp,
            "revenue_eur": round((volume_l - spoil_volume_l) * beer["price_per_l"], 2),
            "cost_eur": round(volume_l * beer["cost_per_l"], 2)
        })
        sales_id += 1

sales_df = pd.DataFrame(sales_list)

# Сохранение файлов
beers.to_csv("dim_beers.csv", index=False)
bars.to_csv("dim_bars.csv", index=False)
breweries.to_csv("dim_breweries.csv", index=False)
batches_df.to_csv("fact_batches.csv", index=False)
sales_df.to_csv("fact_sales.csv", index=False)

print("Все 5 файлов (включая fact_batches и dim_breweries) успешно сгенерированы!")